// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DailyData struct {
	Date             Date  `json:"date"`
	StartupTime      Clock `json:"startupTime"`
	ProducedEnergy   int   `json:"producedEnergy"`
	CumulativeEnergy int   `json:"cumulativeEnergy"`
}

type MinuteData struct {
	Date Date  `json:"date"`
	DcI  []int `json:"dcI"`
}

type Query struct {
}

type ZappiData struct {
	ZappiSn        int     `json:"zappi_sn"`
	PluggedIn      Time    `json:"plugged_in"`
	Unplugged      Time    `json:"unplugged"`
	ChargeDuration int     `json:"charge_duration"`
	Electricity    float64 `json:"electricity"`
}
